[package]
name = "double_delay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.3"

[lib]
name = "double_delay"
crate-type = ["cdylib"]

